apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: saurabh-canary-demo-app
description: main application pipeline
serialPipeline:
  stages:
  - targetId: canary
    profiles: []
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        percentages: [50]
  - targetId: dev
    profiles: []
    strategy:
      standard:
        verify: false
    requiresApproval: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: canary
description: Canary Target
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1
  service: cloud-run-app-saurabh

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev Run Service
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1
  service: cloud-run-app-saurabh
