steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-saurabh/cloud-run-app-saurabh:$SHORT_SHA',
        '.'
      ]
    id: 'Build Docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-saurabh/cloud-run-app-saurabh:$SHORT_SHA'
      ]
    id: 'Push to Artifact Registry'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'cloud-run-app-saurabh',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-saurabh/cloud-run-app-saurabh:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'VERSION=$SHORT_SHA'
      ]
    id: 'Deploy to Cloud Run'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', 'release-$SHORT_SHA',
        '--project=$PROJECT_ID',
        '--region=us-central1',
        '--delivery-pipeline=saurabh-canary-demo-app',
        '--images=cloud-run-app-saurabh=us-central1-docker.pkg.dev/$PROJECT_ID/sales-prediction-saurabh/cloud-run-app-saurabh:$SHORT_SHA'
      ]
    id: 'Trigger Cloud Deploy'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: cloud-run-app-saurabh
h

